### ISSUE TITLE
Tại sao 4 đọc là bốn mà 24 đọc là hai mươi tư mà không phải là hai mươi bốn?

### ISSUE THREAD

**Issue by nguyentranchung** [phpviet/number-to-words#5]

**Comment by vuongxuongminh** [comment]
Khi mình xây dựng thư viện này mình đã kham khảo bài viết sau: https://vndoc.com/cach-doc-viet-dung-so-tu-nhien/download trong trường hợp với số 4 nhiều nơi đọc là hai mươi tư, ba mươi tư nhưng với mình thì vẫn đọc là bốn như mô tả của bạn. Do đặc tính Tiếng Việt phong phú nên mình đã xây dựng mẫu trừu tượng `DictionaryInterface` dành cho trường hợp muốn implement lại cách đọc, còn về standard thì mình đang dựa vào bài mô tả trên.

**Comment by nguyentranchung** [comment]
Theo wiki https://vi.wikipedia.org/wiki/Ch%E1%BB%AF_s%E1%BB%91_Vi%E1%BB%87t_Nam

Khi đứng ở hàng đơn vị của các số từ 21 đến 91, 4 có thể được đọc là "tư"

Vậy "tư" là cách đọc khác cùng ngữ nghĩa, chứ độ ưu tiên của nó vẫn sau "bốn"

**Comment by nguyentranchung** [comment]
Khi số 4 xuất hiện ở hàng đơn vị mà hàng chục không phải là 0, 1 thì sử dụng từ Hán Việt "tư／四".

**Comment by vuongxuongminh** [comment]
Bạn nói đúng, độ ưu tiên của "tư" nên sau "bốn", cảm ơn bạn. Bạn có muốn tạo PR để đóng góp không?
